Default: &defaults
  user: yesod-cwl
  password: yesod-cwl
  host: localhost
  port: 5432
  database: yesod_cwl
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: yesod_cwl_test
  <<: *defaults

Staging:
  database: yesod_cwl_staging
  poolsize: 100
  <<: *defaults

Production:
  database: yesod_cwl_production
  poolsize: 100
  <<: *defaults
